"""SINIM variable catalog: data model, API builder, and local cache I/O.

The catalog is built from ``obtener_datos_filtros.php`` (see ``CLAUDE.md``)
and packaged as ``data/catalog.json`` so the library can work offline for
metadata lookups (:meth:`mcp_sinim.client.SINIMClient.catalog`,
:meth:`mcp_sinim.client.SINIMClient.search`).
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any

import pandas as pd

#: Packaged catalog location, relative to the repository root
#: (``data/catalog.json``), generated by :func:`save_catalog`.
DEFAULT_CATALOG_PATH = Path(__file__).resolve().parent.parent / "data" / "catalog.json"

#: Columns of the tidy catalog DataFrame produced by :func:`build_catalog`.
CATALOG_COLUMNS = ["code", "name", "area", "subarea", "unit", "source"]


@dataclass(frozen=True, slots=True)
class Variable:
    """A single SINIM catalog entry."""

    code: str
    name: str
    area: str
    subarea: str
    unit: str
    source: str


def build_catalog(raw: dict[str, Any]) -> pd.DataFrame:
    """Build a tidy catalog DataFrame from the raw SINIM API payload.

    Parameters
    ----------
    raw:
        Parsed JSON from ``obtener_datos_filtros.php`` — a mapping of
        subarea name to a list of variable metadata dicts (``id_area``,
        ``nombre_area``, ``id_subarea``, ``nombre_subarea``,
        ``unidad_medida_simbolo``, ``unidad_medida_nombre``,
        ``fuente_nombre``, ``id_dato``, ``mtro_datos_nombre``).

    Returns
    -------
    pandas.DataFrame
        Columns: :data:`CATALOG_COLUMNS`.
    """
    raise NotImplementedError


def load_catalog(path: str | Path | None = None) -> pd.DataFrame:
    """Load the packaged (or a custom) catalog JSON as a DataFrame.

    Parameters
    ----------
    path:
        Path to a catalog JSON file. Defaults to :data:`DEFAULT_CATALOG_PATH`.

    Returns
    -------
    pandas.DataFrame
        Columns: :data:`CATALOG_COLUMNS`.
    """
    raise NotImplementedError


def save_catalog(df: pd.DataFrame, path: str | Path | None = None) -> None:
    """Persist a catalog DataFrame to disk as JSON.

    Parameters
    ----------
    df:
        Catalog DataFrame as returned by :func:`build_catalog`.
    path:
        Destination path. Defaults to :data:`DEFAULT_CATALOG_PATH`.
    """
    raise NotImplementedError
