"""SINIM variable catalog: data model, API builder, and local cache I/O.

The catalog is built from ``obtener_datos_filtros.php`` (see ``CLAUDE.md``)
and packaged as ``mcp_sinim/data/catalog.json`` so the library can work
offline for metadata lookups (:meth:`mcp_sinim.client.SINIMClient.catalog`,
:meth:`mcp_sinim.client.SINIMClient.search`).
"""

from __future__ import annotations

import json
from dataclasses import asdict, dataclass
from importlib import resources
from pathlib import Path
from typing import Any

#: Packaged catalog location, next to this module (``mcp_sinim/data/catalog.json``),
#: generated by :func:`save_catalog`. Used as a fallback when
#: :func:`importlib.resources` lookup fails (e.g. a zipped/namespace install).
DEFAULT_CATALOG_PATH = Path(__file__).resolve().parent / "data" / "catalog.json"

#: Field order of the tidy catalog records produced by :func:`build_catalog`
#: and persisted by :func:`save_catalog`.
CATALOG_FIELDS = ["code", "name", "area", "subarea", "unit", "unit_name", "source"]


@dataclass(frozen=True, slots=True)
class Variable:
    """A single SINIM catalog entry.

    Normalized from the raw ``obtener_datos_filtros.php`` payload.
    """

    code: str
    name: str
    area: str
    subarea: str
    unit: str
    unit_name: str
    source: str


def _variable_from_raw(entry: dict[str, Any]) -> Variable:
    """Normalize one raw catalog entry (as returned by the SINIM API).

    Maps ``id_dato -> code``, ``mtro_datos_nombre -> name``,
    ``nombre_area -> area``, ``nombre_subarea -> subarea``,
    ``unidad_medida_simbolo -> unit`` (stripped of trailing spaces),
    ``unidad_medida_nombre -> unit_name``, ``fuente_nombre -> source``
    (``None``/missing becomes ``""``).
    """
    return Variable(
        code=str(entry["id_dato"]),
        name=str(entry.get("mtro_datos_nombre") or "").strip(),
        area=str(entry.get("nombre_area") or "").strip(),
        subarea=str(entry.get("nombre_subarea") or "").strip(),
        unit=str(entry.get("unidad_medida_simbolo") or "").strip(),
        unit_name=str(entry.get("unidad_medida_nombre") or "").strip(),
        source=str(entry.get("fuente_nombre") or "").strip(),
    )


def build_catalog(raw: dict[str, Any]) -> list[Variable]:
    """Build a deduplicated list of :class:`Variable` from the raw API payload.

    Parameters
    ----------
    raw:
        Parsed JSON from ``obtener_datos_filtros.php`` — a mapping of
        subarea name to a list of variable metadata dicts (``id_area``,
        ``nombre_area``, ``id_subarea``, ``nombre_subarea``,
        ``unidad_medida_simbolo``, ``unidad_medida_nombre``,
        ``fuente_nombre``, ``id_dato``, ``mtro_datos_nombre``).

    Returns
    -------
    list[Variable]
        One entry per unique ``id_dato`` (code). If the same code appears
        in more than one subarea group, the first occurrence encountered
        (in payload order) wins and later duplicates are dropped.
    """
    seen: dict[str, Variable] = {}
    for entries in raw.values():
        for entry in entries:
            variable = _variable_from_raw(entry)
            seen.setdefault(variable.code, variable)
    return list(seen.values())


def _sort_key(variable: Variable) -> tuple[int, str]:
    """Sort key for catalog persistence: numeric code first, falling back
    to a lexicographic key for any non-numeric code (defensive; SINIM codes
    are numeric in practice)."""
    try:
        return (int(variable.code), variable.code)
    except ValueError:
        return (0, variable.code)


def save_catalog(variables: list[Variable], path: str | Path | None = None) -> None:
    """Persist a list of :class:`Variable` to disk as stable JSON.

    Records are sorted by ``code`` (numeric order) and serialized with
    ``indent=1`` and ``ensure_ascii=False`` so the file diffs cleanly and
    keeps accented characters readable.

    Parameters
    ----------
    variables:
        Catalog entries, as returned by :func:`build_catalog`.
    path:
        Destination path. Defaults to :data:`DEFAULT_CATALOG_PATH`.
    """
    destination = Path(path) if path is not None else DEFAULT_CATALOG_PATH
    destination.parent.mkdir(parents=True, exist_ok=True)
    ordered = sorted(variables, key=_sort_key)
    payload = [asdict(variable) for variable in ordered]
    # newline="" keeps line endings as plain "\n" regardless of platform, so
    # the file diffs cleanly in git.
    with destination.open("w", encoding="utf-8", newline="") as fh:
        json.dump(payload, fh, indent=1, ensure_ascii=False)
        fh.write("\n")


def load_catalog(path: str | Path | None = None) -> list[Variable]:
    """Load a catalog JSON file (as written by :func:`save_catalog`).

    Parameters
    ----------
    path:
        Path to a catalog JSON file. Defaults to :data:`DEFAULT_CATALOG_PATH`.

    Returns
    -------
    list[Variable]
    """
    source = Path(path) if path is not None else DEFAULT_CATALOG_PATH
    with source.open(encoding="utf-8") as fh:
        payload = json.load(fh)
    return [Variable(**record) for record in payload]


def packaged_catalog() -> list[Variable]:
    """Load the catalog packaged with ``mcp_sinim`` (``mcp_sinim/data/catalog.json``).

    ``data/`` lives inside the ``mcp_sinim`` package (see the layout in
    ``CLAUDE.md``), so this anchors on the installed ``mcp_sinim`` package
    via :mod:`importlib.resources` and resolves its ``data/catalog.json``
    resource — this works correctly for editable installs and for wheel
    installs, since ``package-data`` ships it as part of the package (see
    the ``[tool.setuptools.package-data]`` entry in ``pyproject.toml``).
    Falls back to a path relative to this module when that lookup fails
    (e.g. a zipped/namespace install).

    Returns
    -------
    list[Variable]
    """
    try:
        traversable = resources.files("mcp_sinim") / "data" / "catalog.json"
        if traversable.is_file():
            payload = json.loads(traversable.read_text(encoding="utf-8"))
            return [Variable(**record) for record in payload]
    except (ModuleNotFoundError, FileNotFoundError, AttributeError, NotADirectoryError):
        pass
    return load_catalog(DEFAULT_CATALOG_PATH)
